import { printf,strcmp } from "<libc>"

const main = (() => {
	const myperson = (([(this,name) => {
	if (((strcmp)(name,"name"))==(0))
{return (deref ((this)+(8)))

}

if (((strcmp)(name,"age"))==(0))
{return (deref ((this)+(12)))

}

if (((strcmp)(name,"sayhello"))==(0))
{return (deref ((this)+(16)))

}


},(this,name,value) => {
	if (((strcmp)(name,"name"))==(0))
{(deref ((this)+(8))) = (value)

}

if (((strcmp)(name,"age"))==(0))
{(deref ((this)+(12))) = (value)

}

if (((strcmp)(name,"sayhello"))==(0))
{(deref ((this)+(16))) = (value)

}


},"Bob",30,(this) => {
	
(printf)("Hello! My Name is %s and I am %i years old!\n",this.name,this.age)


}]))

(printf)("%s\n",myperson.name)

(printf)("%i\n",myperson.age)

(myperson.sayhello)(myperson)


})

export { main }

