import {
	puts, 
	printf, 
	sleep
} from "<libc>"

const my_other_func = () => 0

const main = () => {
	const x = 5

	const inner_function = () => {
		puts("this is in an inner function!")
		return "this string!"
	}

	puts("Hello, World!")
	printf("x is equal to... %d\n\n", x)

	puts("I'm sleeping for 1 second!")
	sleep(1)
	puts("I'm awake now!\n")

	printf("my other func always returns %d???\n", my_other_func())
	printf("inner function returns '%s'...\n", inner_function())

	return 0
}

export { main }