import { printf } from "<libc>"
import {
	NORMAL_ARRAY_BYTE_OFFSET, // actuall defined in 'uts-info', but linking with that will cause a linker error (double symbol declaration) - FIX!
	value_at 
} from "temp-utils"

const main = (argc, argv) => {
	let i = 0
	let arg

	printf("argc = %i\n", argc)

	while (i < argc)
	{
		// SEE LIB/ FOR ACUTAL SRC OF value_at
		// value_at segfaults for some reason
		arg = value_at(argv, i) // basically arg = argv[i], hopefully implemented in future
		printf("argv[%i] = %s\n", i, arg)
		i+=1
	}

	return 0
}

export { main }